### ISSUE TITLE
UnicodeDecodeError when trying to read file.

### ISSUE THREAD

**Issue by twanh** [twanh/note-system#14]
Error:
```
Traceback (most recent call last):
  File "/home/twanh/workspace/note-system/.venv/bin/notesystem", line 11, in <module>
    load_entry_point('notesystem==0.0.0', 'console_scripts', 'notesystem')()
  File "/home/twanh/workspace/note-system/.venv/lib/python3.8/site-packages/notesystem/__main__.py", line 6, in run
    main()
  File "/home/twanh/workspace/note-system/.venv/lib/python3.8/site-packages/notesystem/notesystem.py", line 136, in main
    check_mode.start(mode_options)
  File "/home/twanh/workspace/note-system/.venv/lib/python3.8/site-packages/notesystem/modes/base_mode.py", line 62, in start
    self._run(options['args'])  # type: ignore
  File "/home/twanh/workspace/note-system/.venv/lib/python3.8/site-packages/notesystem/modes/check_mode/check_mode.py", line 193, in _run
    errors = self._check_dir(args['in_path'])
  File "/home/twanh/workspace/note-system/.venv/lib/python3.8/site-packages/notesystem/modes/check_mode/check_mode.py", line 69, in _check_dir
    doc_errors = self._check_file(file)
  File "/home/twanh/workspace/note-system/.venv/lib/python3.8/site-packages/notesystem/modes/check_mode/check_mode.py", line 95, in _check_file
    lines = md_file.readlines()
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x91 in position 14: invalid start byte
```

Possible causes:
- Perhaps uncommon emoji?
- `0x91`  utf-8 byte?

Possible fixes:
- Catch UnicodeDecodeError and skip file

**Comment by twanh** [comment]
Seems to appear in `visual.py`

```
- Traceback (most recent call last):
  File "/home/twanh/workspace/note-system/.venv/bin/notesystem", line 11, in <module>
    load_entry_point('notesystem==0.0.0', 'console_scripts', 'notesystem')()
  File "/home/twanh/workspace/note-system/.venv/lib/python3.8/site-packages/notesystem/__main__.py", line 6, in run
    main()
  File "/home/twanh/workspace/note-system/.venv/lib/python3.8/site-packages/notesystem/notesystem.py", line 136, in main
    check_mode.start(mode_options)
  File "/home/twanh/workspace/note-system/.venv/lib/python3.8/site-packages/notesystem/modes/base_mode.py", line 62, in start
    self._run(options['args'])  # type: ignore
  File "/home/twanh/workspace/note-system/.venv/lib/python3.8/site-packages/notesystem/modes/check_mode/check_mode.py", line 237, in _run
    print_doc_error(error)
  File "/home/twanh/workspace/note-system/.venv/lib/python3.8/site-packages/notesystem/common/visual.py", line 29, in print_doc_error
    print(
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 48-50: surrogates not allowed

```
